image: poum/distzilla

stages:
  - test
  - release

test:
  stage: test
  before_script:
    - dzil authordeps --missing          | xargs -n 5 -P 10 cpanm --no-interactive --notest --quiet
    - dzil listdeps   --missing --author | xargs -n 5 -P 10 cpanm --no-interactive --notest --quiet
  script:
    - dzil cover
  only:
    refs:
      - master
      - merge_requests
    changes:
      - '**/*.pm'
      - '**/*.t'

# Runs an automated CPAN release. Testing is not required for tags as `dzil release`
# bundles tests (and fails if the tests fail).
release:
  stage: release
  before_script:
    - dzil authordeps --missing          | xargs -n 5 -P 10 cpanm --no-interactive --notest --quiet
    - dzil listdeps   --missing --author | xargs -n 5 -P 10 cpanm --no-interactive --notest --quiet
    - mkdir -p ~/.dzil
    - echo -e "[%PAUSE]\\nusername = ${PAUSE_USERNAME}\\npassword = ${PAUSE_PASSWORD}\\n" > ~/.dzil/config.ini
  script:
    - dzil release
  only:
    refs:
      - tags
