name: 'perl-release'

on:
  release:
    types: [ published ]

jobs:
  release:
    runs-on: 'ubuntu-latest'
    container:
      image: 'poum/distzilla'
    steps:
      - name: Install git
        run: apt-get update && apt-get install -y git
      - name: 'Get the tag name'
        run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF#refs/*/}
      - name: 'Check out the code'
        uses: 'actions/checkout@v2'
      - name: 'Switch to the tag'
        run: git checkout $RELEASE_VERSION
      - name: 'Install dependencies'
        run: |
          dzil authordeps --missing | xargs -n 5 -P 10 cpanm --no-interactive --notest --quiet
          dzil listdeps --missing --author | xargs -n 5 -P 10 cpanm --no-interactive --notest --quiet
      - name: 'Create the credential file'
        run: |
          echo -e "username=${PAUSE_USERNAME}\\npassword=${PAUSE_PASSWORD}" > ~/.pause
      - name: 'Release to PAUSE'
        run: dzil test # TODO: switch for release

